import { Metadata } from "next";

export default async function Home() {
  return <main className="relative h-screen">
   
   <h1>Hello akaid</h1>

  </main>;
}

export async function generateStaticProps(): Promise<Metadata> {
  const products = await fetch("")

  return {

    title: "Home",
    description: "Generated by create next app",
    openGraph: {
      type: "website",
      description: "Generated by create next app",
    },

  }

}